
name: Main CI

on:
  push:
    branches:
      - '*'
    tags:        
      - '*'

  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Install Lazarus
      uses: red-prig/setup-lazarus@v3
      with:
        lazarus-version: "3.6"
        with-cache: true

    - name: Hash
      shell: cmd
      working-directory: ./
      run: echo '%GITHUB_SHA:~0,7%' > tag.inc

    - name: Tag
      shell: cmd
      working-directory: ./
      if: startsWith(github.ref, 'refs/tags/')
      run: echo '%GITHUB_REF_NAME%' > tag.inc

    - name: Compile
      shell: cmd
      working-directory: ./
      run: |
        lazbuild -B fpPS4.lpi > nul
        strip fpPS4.exe

    - name: Download
      shell: cmd
      working-directory: ./
      run: |
        curl -k -L -s https://github.com/red-prig/fpps4-bin/raw/main/ffmpeg.zip -o ffmpeg.zip
        unzip ffmpeg.zip

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      with:
        name: fpPS4
        path: |
          fpPS4.exe
          *.dll
        if-no-files-found: warn

    - name: Pack
      shell: cmd
      working-directory: ./
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir sce_module
        echo "Put libSceNgs2.prx and etc. here" > sce_module/info.txt
        zip -9 -qq -r "fpPS4_%GITHUB_REF_NAME%.zip" "fpPS4.exe" "*.dll" "sce_module/info.txt"

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./fpPS4_${{ github.ref_name }}.zip
